version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: your-app-image
    container_name: laravel_app
    restart: unless-stopped
    ports:
      - "8010:80"
    depends_on:
      - db
    networks:
      - laravel
  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: athena
      MYSQL_USER: athena
      MYSQL_PASSWORD: Cop1973?
      MYSQL_ROOT_PASSWORD: Cop1973?
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: Cop1973?
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - laravel

  horizon:
    build:
      context: .
      dockerfile: Dockerfile
    image: your-horizon-image
    container_name: laravel_horizon
    command: php artisan horizon
    depends_on:
      - app
      - db
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  dbdata:
