version: '3.8'

services:
  laravel:
    restart: unless-stopped
    container_name: athena-app
    #image: ${DOCKER_IMAGE_URL}
    build:
      context: .
      args:
        - USER_ID=1000
        - GROUP_ID=1000
      dockerfile: Dockerfile
    #volumes:
    #  - .:/var/www/html/:cached
    environment:
      APP_NAME: ${APP_NAME}
      APP_ENV: ${APP_ENV}
      APP_DEBUG: ${APP_DEBUG}
      APP_KEY: ${APP_KEY}
      APP_URL: ${APP_URL}
      DB_CONNECTION: mysql
      DB_HOST: database
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8010:80"
    expose:
      - "8010"
    networks:
      - n-laravel
    depends_on:
      - database

  database:
    restart: unless-stopped
    image: mariadb:lts-jammy
    volumes:
      - v-database:/var/lib/mysql
    environment:
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - n-laravel

volumes:
  v-database:

networks:
  n-laravel:
    driver: bridge