name: Build & Deploy to Stage

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  build-deploy:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - php-version: 8.3
            experimental: true
            composer_args: "--optimize-autoloader --no-interaction --prefer-dist --ignore-platform-reqs --no-scripts"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: intl, zip, gd, pdo_mysql, opcache, pcntl, bcmath, sockets, exif, imagick, redis, apcu, memcached, mongodb

      - name: Validate composer.json
        run: composer validate

      - name: Install dependencies
        run: |
          php -v
          composer -V
          cp .env.development .env
          composer install
        env:
          COMPOSER_CACHE_DIR: /var/www/caches/composer_cache

      - name: Setup Laravel
        run: |
          php -v
          php artisan --version
          php artisan about
          php artisan key:generate
          sqlite3 testing "VACUUM;"
          php artisan migrate
          php artisan module:seed
          php artisan test
          rm -rf testing

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.OWNER_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./.github/deploy/production/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/myapp:latest